name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the
        existing and past issues](https://github.com/containers/ramalama/issues).
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please explain your issue
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce the issue
      description: Please explain the steps to reproduce the issue
    validations:
      required: true
  - type: textarea
    id: received_results
    attributes:
      label: Describe the results you received
      description: Please explain the results you are noticing
    validations:
      required: true
  - type: textarea
    id: expected_results
    attributes:
      label: Describe the results you expected
      description: Please explain the results you are expecting
    validations:
      required: true
  - type: textarea
    id: ramalama_info
    attributes:
      label: ramalama info output
      description: Please copy and paste ramalama info output.
      render: yaml
    validations:
      required: true
  - type: dropdown
    id: upstream_latest
    attributes:
      label: Upstream Latest Release
      description: Have you tried running the [latest upstream release](https://github.com/containers/podman/releases/latest)
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: additional_environment
    attributes:
      label: Additional environment details
      description: Please describe any additional environment details like (AWS, VirtualBox,...)
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description: Please explain the additional information you deem important
    validations:
      required: false
