name: ci
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install bats
        shell: bash
        run: |
           sudo apt-get update
           sudo apt-get install podman bats bash codespell python3-argcomplete pipx
           make install-requirements
      - name: Print disk space before cleanup
        shell: bash
        run: |
           df -h
      - name: Free Disk Space Linux
        shell: bash
        run: |
           sudo docker rmi "$(docker image ls -aq)" >/dev/null 2>&1 || true
           sudo rm -rf \
              /usr/share/dotnet /usr/local/lib/android /opt/ghc \
              /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
              /usr/lib/jvm || true

      # /mnt has ~ 65 GB free disk space. / is too small.
      - name: Reconfigure Docker data-root
        run: |
           sudo mkdir -p /mnt/docker /etc/docker
           echo '{"data-root": "/mnt/docker"}' > /tmp/daemon.json
           sudo mv /tmp/daemon.json /etc/docker/daemon.json
           cat /etc/docker/daemon.json
           sudo systemctl restart docker.service
           df -h


      - name: Print disk space after cleanup
        shell: bash
        run: |
           df -h

      - name: run bats
        run: |
           make validate
           make bats

      - name: bats-nocontainer
        run: |
           pip install tqdm --break-system-packages
           make bats-nocontainer

  docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install bats
        shell: bash
        run: |
           sudo apt-get update
           sudo apt-get install bats bash codespell python3-argcomplete pipx
           make install-requirements
      - name: Print disk space before cleanup
        shell: bash
        run: |
           df -h
      - name: Free Disk Space Linux
        shell: bash
        run: |
           sudo docker rmi "$(docker image ls -aq)" >/dev/null 2>&1 || true
           sudo rm -rf \
              /usr/share/dotnet /usr/local/lib/android /opt/ghc \
              /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
              /usr/lib/jvm || true

      # /mnt has ~ 65 GB free disk space. / is too small.
      - name: Reconfigure Docker data-root
        run: |
           sudo mkdir -p /mnt/docker /etc/docker
           echo '{"data-root": "/mnt/docker"}' > /tmp/daemon.json
           sudo mv /tmp/daemon.json /etc/docker/daemon.json
           cat /etc/docker/daemon.json
           sudo systemctl restart docker.service
           df -h

      - name: Print disk space after cleanup
        shell: bash
        run: |
           df -h

      - name: bats-docker
        run: |
           docker info
           pip install tqdm --break-system-packages
           make bats-docker

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: install golang
        shell: bash
        run: |
           brew install go bats bash jq
           make install-requirements
      - name: Run a one-line script
        shell: bash
        run: |
           make install-requirements
           make validate
           pipx install .
           make bats-nocontainer

# FIXME: ci script should be able to run on MAC.
#      - name: Run ci
#        shell: bash
#        run: make ci
