name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  bats:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install bats
        shell: bash
        run: |
           sudo apt-get update
           sudo apt-get install podman bats bash codespell python3-argcomplete pipx
           make install-requirements

      - name: run bats
        run: |
           make validate
           make bats

  bats-nocontainer:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install bats
        shell: bash
        run: |
           sudo apt-get update
           sudo apt-get install podman bats bash codespell python3-argcomplete pipx
           make install-requirements

      - name: bats-nocontainer
        run: |
           pip install tqdm --break-system-packages
           make bats-nocontainer

  docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install bats
        shell: bash
        run: |
           sudo apt-get update
           sudo apt-get install bats bash codespell python3-argcomplete pipx
           make install-requirements

      - name: build image
        run: |
          make build cpuonly

      - name: bats-docker
        run: |
           docker info
           pip install tqdm --break-system-packages
           make bats-docker

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: install golang
        shell: bash
        run: |
           brew install go bats bash jq
           make install-requirements
      - name: Run a one-line script
        shell: bash
        run: |
           make install-requirements
           make validate
           pipx install .
           make bats-nocontainer

# FIXME: ci script should be able to run on MAC.
#      - name: Run ci
#        shell: bash
#        run: make ci
